### ISSUE TITLE
fix malformed HTML in Test ID 4.C

### ISSUE THREAD

**Issue by robfentress** [Section508Coordinators/TrustedTester#1]
On the [Trusted Tester public draft page](https://section508coordinators.github.io/TrustedTester/), starting in step 4.C, the HTML appears to be malformed, resulting in some closing tags being visible to the end user, and for formatting to appear as if the page contains nested tables.

![screen shot 2018-12-17 at 9 47 11 am](https://user-images.githubusercontent.com/9356499/50094282-d9ce7880-01e0-11e9-9975-d34f72e3e246.png)

**Comment by AnnMarieDavis** [comment]
Thanks for point this out! We appreciate your input. It has been fixed.
