### ISSUE TITLE
Bad Link in TT Section 508 Conformance Test Process for Web PDF

### ISSUE THREAD

**Issue by raebened** [Section508Coordinators/TrustedTester#3]
Page 3 paragraph 1 of the pdf online at https://training.section508testing.net/pluginfile.php/39384/mod_resource/content/6/Trusted%20Tester%20Test%20Process%20v5.0.pdf 

reads,  Please refer to the DHS Section 508 Compliance Testing Tools website at https://www.dhs.gov/508-tools for the most up to date test environment information and the Trusted Tester Test Tool Installation Guide. 

The underlying link reads "edit.dhs.gov/508-tools" and link redirects to https://www.dhs.gov/

**Comment by AnnMarieDavis** [comment]
This link goes to the [https://edit.dhs.gov/508-tools] as designed. You must then select either Web Tools or Software Tools to display the current testing tools and installation guidance.
